// "use client";
import Navbar from "@/component/navbar";
import "./globals.css";

import { Poppins } from "next/font/google";
import QueryProvider from "@/queryProvider/queryProvider";
// import { Provider } from "react-redux";
// import { store } from "../RTK/store";
import ProviderRtk from "../RTK/rtkProvider";
const inter = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <QueryProvider>
        {/* <Provider store={store}> */}
        <ProviderRtk>
          {" "}
          {/* this is just a wrapper */}
          <body className={inter.className}>
            <Navbar />
            {children}
          </body>
        </ProviderRtk>
        {/* </Provider> */}
      </QueryProvider>
    </html>
  );
}
